version: '3.8'
services:
  db: 
    image: postgres:15.2-alpine
    volumes:
      - foodgram_data:/var/lib/postgresql/data
    env_file:
      - ./.env
  web:
    platform: linux/amd64  
    build:
      context: ../backend
    restart: always
    volumes:
      - static_value:/app/django_static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    platform: linux/amd64
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/django_static/
      - media_value:/var/html/media/
    depends_on:
      - web

volumes:
  static_value:
  media_value:
  foodgram_data:
