# Generated by Django 4.1.7 on 2023-04-18 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_tag_options'),
        ('recipe', '0002_remove_recipe_is_in_shopping_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='tags.tag'),
        ),
    ]
