# Generated by Django 4.1.7 on 2023-06-27 18:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0002_alter_tag_options"),
        ("recipe", "0004_recipe_ingredients_alter_recipeingredient_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="pub_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recipetag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="tags.tag",
                unique=True,
            ),
        ),
    ]
