# Generated by Django 4.1.7 on 2023-02-23 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipe_is_favorited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(43200, 'Вы указали время приготовления большечем один месяц, вы уверены вкорректности введённых данных?'), django.core.validators.MinValueValidator(1, 'Время приготовления не можетбыть меньше одной минуты')], verbose_name='Время на приготовление в минутах'),
        ),
    ]
