# Generated by Django 4.1.7 on 2023-06-27 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0002_alter_tag_options"),
        ("recipe", "0005_recipe_pub_date_alter_recipetag_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipetag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="tags.tag",
            ),
        ),
    ]
