# Generated by Django 4.1.7 on 2023-02-23 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0006_remove_recipe_is_favorited_favoriterecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriterecipe',
            name='who_favorited',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_favorited', to=settings.AUTH_USER_MODEL),
        ),
    ]
