# Generated by Django 4.1.7 on 2023-02-23 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0007_alter_favoriterecipe_who_favorited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriterecipe',
            name='favorited_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_favorited', to='recipe.recipe'),
        ),
        migrations.AlterField(
            model_name='favoriterecipe',
            name='who_favorited',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
