# Generated by Django 4.1.7 on 2023-07-01 12:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipe", "0008_alter_recipeingredient_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="author",
            field=models.ForeignKey(
                help_text="Author of the recipe",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(default=None, upload_to="recipes/"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="name",
            field=models.CharField(
                help_text="Name of the recipe", max_length=80, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "вес не может быть меньше однойединицы измерения продукта"
                    )
                ],
                verbose_name="количество",
            ),
        ),
    ]
