# Generated by Django 4.1.7 on 2023-07-07 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0009_alter_recipe_author_alter_recipe_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(
                        43200, "Time of cooking cannot exceed one month"
                    ),
                    django.core.validators.MinValueValidator(
                        1, "The cooking tine cannot be less than 1 minute"
                    ),
                ],
                verbose_name="time for cooking in minutes",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="text",
            field=models.TextField(max_length=500, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "the weight cannot be less than 1"
                    )
                ],
                verbose_name="quantity",
            ),
        ),
    ]
