# Generated by Django 4.1.7 on 2023-07-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0010_alter_recipe_cooking_time_alter_recipe_text_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="recipetag",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="recipetag",
            constraint=models.UniqueConstraint(
                fields=("tag", "recipe"), name="unique tag-recipe pair"
            ),
        ),
    ]
