# Generated by Django 4.1.7 on 2023-02-24 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0014_alter_recipeingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0.1, validators=[django.core.validators.MinValueValidator(0.1, 'вес не может быть меньше одной десятойот одной единицы измерения')], verbose_name='количество'),
        ),
    ]
