# Generated by Django 4.1.7 on 2023-02-24 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0016_alter_recipeingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1, 'вес не может быть меньше одной десятойот одной единицы измерения')], verbose_name='количество'),
        ),
    ]
