# Generated by Django 4.1.7 on 2023-04-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тэг')),
                ('color', models.CharField(max_length=50, unique=True, verbose_name='Цвет')),
                ('slug', models.SlugField(unique=True, verbose_name='Cсылка')),
            ],
        ),
    ]
