# Generated by Django 4.1.7 on 2023-07-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0002_alter_tag_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                help_text="Введите цвет в HEX формате",
                max_length=7,
                unique=True,
                verbose_name="Цвет",
            ),
        ),
    ]
