# Generated by Django 4.1.7 on 2023-07-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0003_alter_tag_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                help_text="Color in HEX format",
                max_length=7,
                unique=True,
                verbose_name="Color",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="Tag"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Slug"),
        ),
    ]
