# Generated by Django 4.1.7 on 2023-03-04 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_name_user_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
    ]
