# Generated by Django 4.1.7 on 2023-02-24 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0.1, verbose_name=django.core.validators.MinValueValidator(0.1, 'вес не может быть меньше одной десятойот одной единицы измерения')),
            preserve_default=False,
        ),
    ]
