# Generated by Django 4.1.7 on 2023-02-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_ingredient_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='amount',
        ),
    ]
