# http://127.0.0.1:8000/api/recipes/?page=1&limit=6&author=2&tags=black


# http://127.0.0.1:8000/api/recipes/tags=black
# http://127.0.0.1:8000/api/recipes/
# http://127.0.0.1:8000/api/recipes/?page=1&limit=6&tags=special_link

http://127.0.0.1/api/auth/login
content-type: application/json


http://127.0.0.1/api/recipes/?page=1
content-type: application/json
Authorization: token 4897fa3e9cf42d4db4bf303b76d9cc9be4734d0e