# http://127.0.0.1:8000/api/recipes/?page=1&limit=6&author=2&tags=black


# http://127.0.0.1:8000/api/recipes/tags=black
# http://127.0.0.1:8000/api/recipes/
# http://127.0.0.1:8000/api/recipes/?page=1&limit=6&tags=special_link

# http://127.0.0.1/api/auth/login
# content-type: application/json



# http://localhost/api/recipes/
# http://localhost/api/recipes/31/
# http://localhost/api/users/me/
GET http://127.0.0.1:8000/api/recipes/download_shopping_cart/ HTTP/1.1
content-type: application/json
Authorization: Token 0f7f4692b1998b10ac2a66116a53380f761eac64