# http://127.0.0.1:8000/api/recipes/?page=1&limit=6&author=2&tags=black


# http://127.0.0.1:8000/api/recipes/tags=black
# http://127.0.0.1:8000/api/recipes/
# http://127.0.0.1:8000/api/recipes/?page=1&limit=6&tags=special_link
http://127.0.0.1:8000/api/recipes/?page=1&limit=6&author=20&tags=speclink
content-type: application/json
Authorization: token 0f7f4692b1998b10ac2a66116a53380f761eac64