
# POST http://127.0.0.1:8000/api/users/ HTTP/1.1
# content-type: application/json
# Authorization: token 0f7f4692b1998b10ac2a66116a53380f761eac64

# {
#   "email": "user19@yandex.ru",
#   "username": "user19.pupkin",
#   "first_name": "user19",
#   "last_name": "user19",
#   "password": "Qwerty17"
# }


# admin in docker 0f7f4692b1998b10ac2a66116a53380f761eac64


# # POST http://127.0.0.1/api/auth/token/login/ HTTP/1.1

# GET http://127.0.0.1/api/users

# POST http://127.0.0.1:8000/api/auth/token/login/ HTTP/1.1
# content-type: application/json

# {
#     "email": "admin@admin.com",
#     "password": "admin"
# }


# GET http://127.0.0.1:8000/api/users/me/ HTTP/1.1
# content-type: application/json
# Authorization: token 0f7f4692b1998b10ac2a66116a53380f761eac64


# GET http://127.0.0.1:8000/api/recipes?author=me HTTP/1.1 OK
# GET http://127.0.0.1:8000/api/recipes/32/ HTTP/1.1
# content-type: application/json
# Authorization: token 0f7f4692b1998b10ac2a66116a53380f761eac64


# GET http://127.0.0.1:8000/api/test/
# GET http://127.0.0.1:8000/api/recipes/32/ HTTP/1.1
# content-type: application/json
# Authorization: token 0f7f4692b1998b10ac2a66116a53380f761eac64

# POST http://127.0.0.1:8000/api/recipes/ HTTP/1.1
# content-type: application/json
# authorization: token 0f7f4692b1998b10ac2a66116a53380f761eac64

# {
#   "ingredients": [
#       {"id": 1, "amount": 10}
#   ],
#   "tags": [1, 2],
#   "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
#   "name": "string_rec",
#   "text": "string",
#   "cooking_time": 1
# }

GET  http://127.0.0.1:8000/api/recipes/82/ HTTP/1.1

GET http://127.0.0.1:8000/api/recipes/download_shopping_cart/ HTTP/1.1
content-type: application/json
authorization: token 0f7f4692b1998b10ac2a66116a53380f761eac64

# {
#   "ingredients": [
#     {
#       "id": 2,
#       "amount": 10
#       }],
#       "tags": [1, 2 ],
#       "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
#       "name": "string",
#       "text": "string",
#       "cooking_time": 1
# }


# log.info(f'it is an instance {instance}')
# INFO it is an instance id 82: string_rec

# log.info(ingredient)
# INFO [OrderedDict([('id', <Ingredient: id 1: Капуста в кг>), ('amount', 10)])]

# ingredient=ingredient['id']