
# content-type: application/json
# Authorization: token 0f7f4692b1998b10ac2a66116a53380f761eac64


# ПОДПИСКИ
# POST  http://127.0.0.1:8000/api/users/11/subscribe/ HTTP/1.1
# DELETE http://127.0.0.1:8000/api/users/11/subscribe/ HTTP/1.1
GET http://127.0.0.1:8000/api/users/subscriptions/ HTTP/1.1
content-type: application/json
Authorization: token 0f7f4692b1998b10ac2a66116a53380f761eac64